const c=document.getElementById('game'),ctx=c.getContext('2d'),W=c.width,H=c.height,keys={};let running=false,paused=false,last=0,won=false,t=0,shake=0,heroName='Robot Bear',hp=5,tickets=0,secrets=0,phase=0,pulses=[],enemies=[],boss=null;
const heroes=[{name:'Robot Bear',icon:'🐻🤖',ability:'Щит: понася допълнителен удар'},{name:'Snow Woman',icon:'❄️',ability:'Лед: забавя враговете'},{name:'Robotic Hand',icon:'🦾',ability:'Сила: двойни щети'},{name:'RH.exe',icon:'📡',ability:'Обсег: далечна атака'},{name:'Tiny Man',icon:'👤',ability:'Спринт: по-бързо движение'}];
let p={x:80,y:620,r:19,s:230,cd:0,inv:0,shield:1,dir:1,bob:0};
const walls=[{x:0,y:205,w:1280,h:22},{x:0,y:698,w:1280,h:22},{x:180,y:250,w:45,h:300},{x:360,y:205,w:35,h:270},{x:360,y:555,w:35,h:143},{x:540,y:320,w:45,h:378},{x:720,y:205,w:35,h:300},{x:720,y:585,w:35,h:113},{x:920,y:300,w:45,h:398},{x:1090,y:205,w:35,h:300}];
const mirrors={x:455,y:260,done:false},carousel={x:650,y:520,on:true},trapdoor={x:845,y:625,open:false},bossGate={x:1090,y:505,w:35,h:193,open:false};
const ticketItems=[{x:300,y:610,got:false},{x:665,y:270,got:false},{x:1015,y:560,got:false}];
const notes=[{x:285,y:290,got:false,title:'Скъсан плакат',text:'„Последното представление беше отменено. Животните отказаха да доближат гората.“'},{x:625,y:625,got:false,title:'Бележка на механика',text:'„Въртележката се включи сама точно в 03:17. Същият час като крановете в склада.“'},{x:820,y:260,got:false,title:'Детска рисунка',text:'На рисунката клоун държи черен корен. Отдолу пише: „Той не беше такъв преди.“'},{x:1190,y:270,got:false,title:'Страница от дневник',text:'„Музиката идва отдолу. Под арената има тунел, който не е на плановете.“'}];
function sync(){hpEl.textContent=hp;ticketsEl.textContent=tickets;secretsEl.textContent=secrets;bossEl.textContent=boss?Math.max(0,boss.hp)+'%':'—';const m=['Намери 3 циркови билета','Премини Огледалния лабиринт','Спри прокълнатата въртележка','Открий тунела под арената','Победи Маестро Смях'];missionEl.textContent=won?'Циркът е освободен!':m[Math.min(phase,4)]}
const hpEl=document.getElementById('hp'),ticketsEl=document.getElementById('tickets'),secretsEl=document.getElementById('secrets'),bossEl=document.getElementById('boss'),missionEl=document.getElementById('mission');
function msg(s,d=2200){let e=document.getElementById('message');e.textContent=s;e.classList.remove('hidden');clearTimeout(msg.to);msg.to=setTimeout(()=>e.classList.add('hidden'),d)}
function reset(){hp=5;tickets=0;secrets=0;phase=0;won=false;paused=false;t=0;p={x:80,y:620,r:19,s:230,cd:0,inv:0,shield:heroName==='Robot Bear'?2:1,dir:1,bob:0};pulses=[];ticketItems.forEach(q=>q.got=false);notes.forEach(q=>q.got=false);mirrors.done=false;carousel.on=true;trapdoor.open=false;bossGate.open=false;boss=null;enemies=[{x:280,y:430,h:3},{x:470,y:610,h:3},{x:650,y:400,h:3},{x:840,y:450,h:3},{x:1010,y:270,h:4}].map((e,i)=>({...e,max:e.h,slow:0,dx:i%2?1:-1}));sync()}
startBtn.onclick=()=>{overlay.classList.add('hidden');heroGrid.innerHTML='';heroes.forEach(h=>{let b=document.createElement('button');b.innerHTML=`<span class="heroIcon">${h.icon}</span><span class="heroName">${h.name}</span><small class="heroAbility">${h.ability}</small>`;b.onclick=()=>{heroName=h.name;choice.classList.add('hidden');reset();running=true;msg('Добре дошъл в Цирка… музиката започна сама.')};heroGrid.appendChild(b)});choice.classList.remove('hidden')};storyClose.onclick=()=>{story.classList.add('hidden');paused=false};document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{if(b.dataset.m==='2'){b.style.background='#6ed39c';mirrors.done=true;phase=Math.max(phase,2);mirrorHint.textContent='Правилно! Огледалната врата се отвори.';setTimeout(()=>{mirror.classList.add('hidden');paused=false;msg('Зад огледалото откри таен проход.')},650)}else{b.style.background='#c34f5b';mirrorHint.textContent='Това е отражение. Опитай пак.'}});
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('#mobile button').forEach(b=>{let k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys[k]=true;if(k==='KeyE')interact()};b.onpointerup=()=>keys[k]=false});
function rc(r,cx,cy,cr){let nx=Math.max(r.x,Math.min(cx,r.x+r.w)),ny=Math.max(r.y,Math.min(cy,r.y+r.h));return (cx-nx)**2+(cy-ny)**2<cr**2}function solids(){return [...walls,...(bossGate.open?[]:[bossGate])]}function can(nx,ny){return nx>22&&nx<W-22&&ny>230&&ny<H-22&&!solids().some(w=>rc(w,nx,ny,p.r))}function near(o,d=65){return Math.hypot(p.x-o.x,p.y-o.y)<d}
function attack(){if(p.cd>0)return;p.cd=heroName==='Tiny Man'?.38:.55;pulses.push({x:p.x,y:p.y,r:4,a:1,range:heroName==='RH.exe'?370:280,hit:new Set()})}function hitPlayer(x){if(p.inv>0)return;if(p.shield>1){p.shield--;p.inv=.8;msg('Щитът пое удара!');return}hp--;p.inv=1;shake=.25;sync();if(hp<=0){running=false;msg('Опитай отново — презареди страницата.',4000)}}
function interact(){if(!running||paused||won)return;for(const n of notes)if(!n.got&&near(n)){n.got=true;secrets++;sync();storyTitle.textContent=n.title;storyText.textContent=n.text;story.classList.remove('hidden');paused=true;return}if(tickets>=1&&!mirrors.done&&near(mirrors,80)){mirror.classList.remove('hidden');paused=true;phase=Math.max(phase,1);sync();return}if(tickets===3&&carousel.on&&near(carousel,95)){carousel.on=false;phase=3;msg('Въртележката спря. Под нея се чу метално щракване.');sync();return}if(!carousel.on&&!trapdoor.open&&near(trapdoor,85)){trapdoor.open=true;bossGate.open=true;phase=4;boss={x:1180,y:500,hp:100,max:100,cd:1.2,phase:1};msg('Тайният тунел води под голямата шатра… МАЕСТРО СМЯХ те чака!',3500);sync()}}
function update(dt){if(!running||paused||won)return;t+=dt;p.cd=Math.max(0,p.cd-dt);p.inv=Math.max(0,p.inv-dt);p.bob+=dt*7;shake=Math.max(0,shake-dt);let vx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),vy=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),n=Math.hypot(vx,vy)||1,s=p.s*(heroName==='Tiny Man'?1.25:1);if(vx)p.dir=Math.sign(vx);let nx=p.x+vx/n*s*dt,ny=p.y+vy/n*s*dt;if(can(nx,p.y))p.x=nx;if(can(p.x,ny))p.y=ny;if(keys.Space)attack();ticketItems.forEach(q=>{if(!q.got&&near(q,32)){q.got=true;tickets++;msg('Намери цирков билет! '+tickets+'/3');if(tickets===3)phase=Math.max(phase,2);sync()}});pulses.forEach(q=>{q.r+=q.range*dt;q.a-=1.5*dt;enemies.forEach(e=>{if(e.h<=0||q.hit.has(e))return;if(Math.abs(Math.hypot(e.x-q.x,e.y-q.y)-q.r)<28){e.h-=heroName==='Robotic Hand'?2:1;if(heroName==='Snow Woman')e.slow=2;q.hit.add(e)}});if(boss&&boss.hp>0&&!q.hit.has(boss)&&Math.abs(Math.hypot(boss.x-q.x,boss.y-q.y)-q.r)<38){boss.hp-=heroName==='Robotic Hand'?8:5;q.hit.add(boss);if(boss.hp<=50&&boss.phase===1){boss.phase=2;msg('ФАЗА 2: Маестро Смях гаси светлините!',2600)}if(boss.hp<=0){won=true;msg('Маестро Смях е победен!',3000)}sync()}});pulses=pulses.filter(q=>q.a>0);enemies.forEach(e=>{if(e.h<=0)return;e.slow=Math.max(0,e.slow-dt);let d=Math.hypot(p.x-e.x,p.y-e.y),sp=e.slow?28:58;if(d<190){e.x+=(p.x-e.x)/(d||1)*sp*dt;e.y+=(p.y-e.y)/(d||1)*sp*dt}else{e.x+=e.dx*25*dt;if(e.x<240||e.x>1050)e.dx*=-1}if(d<35)hitPlayer(e.x)});if(boss&&boss.hp>0){let d=Math.hypot(p.x-boss.x,p.y-boss.y);boss.cd-=dt;if(boss.phase===2)boss.x=1165+Math.sin(t*2.3)*45;if(boss.cd<0){boss.cd=boss.phase===2?.65:1.1;if(d<260)hitPlayer(boss.x)}if(d<48)hitPlayer(boss.x)}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#22143b');g.addColorStop(.45,'#32152e');g.addColorStop(1,'#090c18');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#17121e';ctx.fillRect(0,205,W,515);for(let x=20;x<W;x+=120){ctx.fillStyle=x%240?'#5e173c':'#7b1d37';ctx.beginPath();ctx.moveTo(x,205);ctx.lineTo(x+60,85);ctx.lineTo(x+120,205);ctx.fill()}ctx.fillStyle='#b68b4533';for(let y=250;y<720;y+=55)ctx.fillRect(0,y,W,2);walls.forEach(w=>{if(w.y===205||w.y===698)return;ctx.fillStyle='#5a2847';rr(w.x,w.y,w.w,w.h,8);ctx.fillStyle='#e7b24a33';ctx.fillRect(w.x+8,w.y+8,w.w-16,5)});drawCarousel();drawMirrors();drawTrap();}
function drawCarousel(){ctx.save();ctx.translate(carousel.x,carousel.y);ctx.rotate(carousel.on?t*.5:0);ctx.fillStyle='#8d2d63';ctx.beginPath();ctx.arc(0,0,70,0,7);ctx.fill();ctx.strokeStyle='#ffd568';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,62,0,7);ctx.stroke();for(let i=0;i<6;i++){ctx.save();ctx.rotate(i*Math.PI/3);ctx.fillStyle='#e6c05e';ctx.fillRect(45,-3,35,6);ctx.fillStyle='#eee';ctx.font='24px sans-serif';ctx.fillText('🎠',58,5);ctx.restore()}ctx.restore()}
function drawMirrors(){ctx.fillStyle=mirrors.done?'#4f786e':'#6880a2';rr(mirrors.x-30,mirrors.y-42,60,84,28);ctx.fillStyle='#bfeaff55';rr(mirrors.x-21,mirrors.y-32,42,62,22)}function drawTrap(){ctx.fillStyle=trapdoor.open?'#071015':'#69492f';ctx.fillRect(trapdoor.x-40,trapdoor.y-24,80,48);ctx.strokeStyle='#c89c5b';ctx.strokeRect(trapdoor.x-40,trapdoor.y-24,80,48)}
function drawTicket(q){if(q.got)return;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(Math.sin(t*2+q.x)*.08);ctx.fillStyle='#ffd968';rr(-17,-10,34,20,4);ctx.fillStyle='#6c2c55';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText('TICKET',0,4);ctx.restore()}function drawNote(n){if(n.got)return;ctx.fillStyle='#f0e2ad';ctx.fillRect(n.x-9,n.y-13,18,26);if(near(n))prompt('E — прочети',n.x,n.y-24)}
function drawEnemy(e){if(e.h<=0)return;ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(0,20,22,7,0,0,7);ctx.fill();ctx.fillStyle='#eee';ctx.beginPath();ctx.arc(0,-5,19,0,7);ctx.fill();ctx.fillStyle='#e64f69';ctx.beginPath();ctx.arc(0,-18,7,0,7);ctx.fill();ctx.fillStyle='#4a1831';ctx.beginPath();ctx.arc(-7,-7,3,0,7);ctx.arc(7,-7,3,0,7);ctx.fill();ctx.strokeStyle='#4a1831';ctx.beginPath();ctx.arc(0,1,9,0,Math.PI);ctx.stroke();ctx.fillStyle='#88436a';ctx.fillRect(-15,14,30,23);ctx.restore()}
function drawBoss(){if(!boss||boss.hp<=0)return;ctx.save();ctx.translate(boss.x,boss.y);let s=boss.phase===2?1.18:1;ctx.scale(s,s);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,42,42,12,0,0,7);ctx.fill();ctx.fillStyle='#eee';ctx.beginPath();ctx.arc(0,-25,34,0,7);ctx.fill();ctx.fillStyle='#e84161';ctx.beginPath();ctx.arc(0,-52,15,0,7);ctx.fill();ctx.fillStyle='#35152b';ctx.beginPath();ctx.arc(-12,-30,5,0,7);ctx.arc(12,-30,5,0,7);ctx.fill();ctx.strokeStyle='#35152b';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-12,18,0,Math.PI);ctx.stroke();ctx.fillStyle='#9b2e66';rr(-28,8,56,55,12);ctx.fillStyle='#ffd45e';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText('МАЕСТРО СМЯХ',0,-70);ctx.restore()}
function drawHero(){ctx.save();ctx.translate(p.x,p.y+Math.sin(p.bob)*2);ctx.scale(p.dir,1);ctx.globalAlpha=p.inv>0&&Math.floor(p.inv*12)%2?.35:1;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(0,26,21,6,0,0,7);ctx.fill();let col={ 'Robot Bear':'#e9f3f8','Snow Woman':'#bdefff','Robotic Hand':'#f0a347','RH.exe':'#66536e','Tiny Man':'#303944'}[heroName];ctx.fillStyle=col;ctx.beginPath();ctx.arc(0,-21,17,0,7);ctx.fill();rr(-15,-5,30,38,9);if(heroName==='Robot Bear'){ctx.beginPath();ctx.arc(-13,-33,7,0,7);ctx.arc(13,-33,7,0,7);ctx.fill()}if(heroName==='RH.exe'){ctx.fillStyle='#ad61ff';ctx.fillRect(-9,-25,18,5)}if(heroName==='Robotic Hand'){ctx.fillStyle='#e85b38';rr(13,-3,24,28,8)}if(heroName==='Snow Woman'){ctx.strokeStyle='#8feaff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(17,0);ctx.lineTo(30,-12);ctx.moveTo(17,0);ctx.lineTo(31,7);ctx.stroke()}ctx.restore()}
function prompt(s,x,y){ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.fillText(s,x,y)}function prompts(){if(tickets>=1&&!mirrors.done&&near(mirrors,80))prompt('E — огледален лабиринт',mirrors.x,mirrors.y-55);if(tickets===3&&carousel.on&&near(carousel,95))prompt('E — спри въртележката',carousel.x,carousel.y-90);if(!carousel.on&&!trapdoor.open&&near(trapdoor,85))prompt('E — отвори люка',trapdoor.x,trapdoor.y-35)}
function winScreen(){ctx.fillStyle='#070a13ed';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 48px system-ui';ctx.fillText('ЦИРКЪТ Е ОСВОБОДЕН!',W/2,H/2-95);ctx.fillStyle='#ffcf67';ctx.font='900 30px system-ui';ctx.fillText('Маестро Смях е победен',W/2,H/2-42);ctx.fillStyle='#9beaff';ctx.font='bold 24px system-ui';ctx.fillText(`Тайни: ${secrets}/4`,W/2,H/2+5);ctx.fillStyle='#fff';ctx.font='18px system-ui';ctx.fillText('Под арената откриваш тунел, който води към… КАНАЛИТЕ.',W/2,H/2+58);ctx.fillStyle='#8deaff';ctx.font='900 31px system-ui';ctx.fillText('СЛЕДВАЩО НИВО: КАНАЛИТЕ',W/2,H/2+110)}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*7,(Math.random()-.5)*7);bg();ticketItems.forEach(drawTicket);notes.forEach(drawNote);enemies.forEach(drawEnemy);drawBoss();pulses.forEach(q=>{ctx.strokeStyle=`rgba(120,225,255,${q.a})`;ctx.lineWidth=6;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.stroke()});drawHero();prompts();if(boss&&boss.phase===2){ctx.fillStyle=`rgba(20,0,30,${.18+.12*Math.sin(t*5)})`;ctx.fillRect(0,0,W,H)}if(won)winScreen();ctx.restore()}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}sync();requestAnimationFrame(loop);
